### ISSUE TITLE
Failed to start systemctl start packetloss-watchdog

### ISSUE THREAD

**Issue by maxbrandes** [cbruegg/packetloss-watchdog#1]
**Describe the bug**
Thanks Chrisitian for the service. Tried to install it on my Raspberry Pi, but get the following issue with make the service ready for boot. Any suggestions? I created the .service file on MacOS and a text file, then renamed the file from a .rtf to the .service, moved it with FileZilla to the Rasperry pi and then to the systemd/system folder with sudo cp. The service has a permission code of 755.

**System Info**
 - OS: Raspbian Linux

<img width="1024" alt="grafik" src="https://user-images.githubusercontent.com/5220611/80951346-43a3ee00-8de7-11ea-999a-d069ad54661d.png">
<img width="722" alt="grafik" src="https://user-images.githubusercontent.com/5220611/80951686-dcd30480-8de7-11ea-9959-172bf76c8c20.png">
<img width="547" alt="grafik" src="https://user-images.githubusercontent.com/5220611/80951743-f411f200-8de7-11ea-9893-4bbd4eca3b03.png">

**Comment by cbruegg** [comment]
Hi Max, I suspect it's because it's an RTF file. Try copying the file content to your clipboard, SSH into your Raspberry Pi and run:

```
sudo rm /etc/systemd/packetloss-watchdog.service
sudo nano /etc/systemd/packetloss-watchdog.service
```

Now paste the clipboard content into your terminal window. Press CTRL+O hit enter and then CTRL+X to exit. That hopefully solves the error.

**Comment by maxbrandes** [comment]
Thanks a lot! Issue resolved.
