### ISSUE TITLE
is this still an issue with the box?

### ISSUE THREAD

**Issue by eskoONE** [cbruegg/packetloss-watchdog#4]
sry for cluttering your bug report with this, but im having issues with an old hitron box and vodafone suggested me to change my router to solve my issues. but now that i came around the web and found out about the issues of the box new vodafone box, i dont rly want swap out my router for one that is apparently worse off than the current one i have.

has the issues been resolved with the box or is the restarting of the box necessary to have it functioning properly?

**Comment by cbruegg** [comment]
Hi, no worries!

For me personally, the issue seems to have disappeared. At least my logs indicate no recent reboot.
